apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-deployment
  labels:
    app: flask-k8s
spec:
  selector:
    matchLabels:
      app: flask-k8s
  replicas: 8
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-k8s
    spec:
      containers:
      - name: flask-k8s
        image: 263884695115.dkr.ecr.eu-west-1.amazonaws.com/sample-test:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "0.5"
            memory: "128Mi"
      priorityClassName: high-priority-apps
---
apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-service
  labels:
    app: flask-k8s
spec:
  selector:
    app: flask-k8s
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
