apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-hpa-memory
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: flask-k8s-deployment
  minReplicas: 8
  maxReplicas: 15 
  metrics: 
  - type: Resource
    resource:
      name: memory 
      targetAverageUtilization: 60

