apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-hpa-cpu
spec:
  maxReplicas: 12
  minReplicas: 8
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-k8s-deployment
  targetCPUUtilizationPercentage: 50
